import type { Challenge } from "./types";

export const CHALLENGES: Challenge[] = [
  {
    id: "alpe-dhuez",
    name: "Alpe d'Huez",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    aliases: ["alpe d'huez", "alpe dhuez", "alpe de huez", "l'alpe d'huez"],
    distance_km: 13.8,
    elevation_gain_m: 1071,
    avg_gradient: 7.9,
    max_gradient: 13,
    difficulty_score: 8,
    min_level: "intermedio-alto",
    description:
      "21 curvas legendarias del Tour de Francia. Pendiente exigente y constante desde el primer kilómetro.",
    elevation_profile: [5, 15, 25, 30, 40, 42, 50, 55, 60, 68, 72, 78, 82, 88, 90, 94, 96, 98, 99, 100],
  },
  {
    id: "mortirolo",
    name: "Passo del Mortirolo",
    region: "Alpes (Francia/Italia)",
    country: "Italia",
    aliases: ["mortirolo", "passo del mortirolo", "passo mortirolo"],
    distance_km: 12.4,
    elevation_gain_m: 1300,
    avg_gradient: 10.5,
    max_gradient: 18,
    difficulty_score: 10,
    min_level: "avanzado",
    description:
      "Uno de los puertos más duros de Europa: rampas de hasta el 18% en un túnel de bosque cerrado.",
    elevation_profile: [10, 35, 50, 60, 65, 70, 74, 78, 82, 85, 88, 90, 92, 94, 96, 97, 98, 99, 100],
  },
  {
    id: "ventoux",
    name: "Mont Ventoux",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    aliases: ["ventoux", "mont ventoux", "mont ventou", "gigante de la provenza"],
    distance_km: 21.5,
    elevation_gain_m: 1617,
    avg_gradient: 7.5,
    max_gradient: 12,
    difficulty_score: 9,
    min_level: "avanzado",
    description:
      "El Gigante de la Provenza: kilómetros de bosque antes del paisaje lunar final, expuesto al mistral.",
    elevation_profile: [5, 12, 20, 28, 35, 42, 50, 58, 65, 72, 80, 86, 90, 94, 97, 99, 100],
  },
  {
    id: "sa-calobra",
    name: "Sa Calobra",
    region: "Mallorca (España)",
    country: "España",
    aliases: ["sa calobra", "coll dels reis", "sa calobra mallorca"],
    distance_km: 9.3,
    elevation_gain_m: 668,
    avg_gradient: 7.1,
    max_gradient: 12,
    difficulty_score: 6,
    min_level: "intermedio",
    description:
      "El famoso 'nudo de corbata' de la Tramuntana. Vistas espectaculares al mar desde cada curva.",
    elevation_profile: [40, 20, 10, 5, 15, 30, 45, 60, 72, 82, 90, 96, 100],
  },
  {
    id: "mount-evans",
    name: "Mount Evans Scenic Byway",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    aliases: ["mount evans", "mt evans", "mount evans scenic byway"],
    distance_km: 45,
    elevation_gain_m: 2100,
    avg_gradient: 4.6,
    max_gradient: 9,
    difficulty_score: 9,
    min_level: "avanzado",
    description:
      "La carretera pavimentada más alta de Norteamérica (4.300 m). El reto aquí es tanto la altitud como el desnivel.",
    elevation_profile: [8, 16, 24, 32, 40, 48, 55, 62, 68, 74, 80, 85, 90, 94, 97, 100],
  },
  {
    id: "serra-do-rio-do-rastro",
    name: "Serra do Rio do Rastro",
    region: "Santa Catarina (Brasil)",
    country: "Brasil",
    aliases: ["serra do rio do rastro", "rio do rastro", "serra catarinense"],
    distance_km: 12,
    elevation_gain_m: 850,
    avg_gradient: 7.2,
    max_gradient: 15,
    difficulty_score: 8,
    min_level: "intermedio-alto",
    description:
      "Curvas de herradura talladas en el acantilado, uno de los miradores más espectaculares de Brasil.",
    elevation_profile: [10, 30, 45, 55, 62, 68, 74, 79, 84, 88, 92, 95, 98, 100],
  },
];
