import type { Partner } from "./types";

export const PARTNERS: Partner[] = [
  // ---- Alpes (Francia/Italia) ----
  {
    id: "op-alps-experience",
    type: "operador",
    name: "Alps Experience",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    min_level: "intermedio-alto",
    services: ["guía en ruta", "soporte mecánico", "furgón de apoyo", "alojamiento"],
    languages: ["Francés", "Inglés", "Español"],
    price_eur: 890,
    price_unit: "paquete de 4 días",
    rating: 4.8,
    reviews_count: 132,
    verified: true,
    why: "Especializado en los grandes puertos alpinos con más de 10 años operando en la región y valoración media de 4.8/5 en reservas confirmadas.",
  },
  {
    id: "op-dolomiti-gravel",
    type: "operador",
    name: "Dolomiti & Gravel Tours",
    region: "Alpes (Francia/Italia)",
    country: "Italia",
    min_level: "intermedio",
    services: ["guía en ruta", "alquiler de gravel", "rutas panorámicas"],
    languages: ["Italiano", "Inglés"],
    price_eur: 650,
    price_unit: "paquete de 3 días",
    rating: 4.6,
    reviews_count: 58,
    verified: true,
    why: "Buena opción si tu nivel es intermedio: combina asfalto y gravel para dosificar el esfuerzo antes del reto principal.",
  },
  {
    id: "coach-marc-dupont",
    type: "coach",
    name: "Marc Dupont — Preparación de montaña",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    min_level: "cualquiera",
    services: ["plan de entrenamiento", "test de umbral", "seguimiento por Strava"],
    certification: "UCI Coaching Level 2",
    languages: ["Francés", "Inglés"],
    price_eur: 220,
    price_unit: "plan de 8 semanas",
    rating: 4.9,
    reviews_count: 74,
    verified: true,
    why: "Certificación UCI y experiencia específica preparando ciclistas para Alpe d'Huez y el Mortirolo.",
  },
  {
    id: "rental-alps-bikes",
    type: "alquiler",
    name: "Alps Bikes Rental",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    min_level: "cualquiera",
    services: ["bicicleta de carretera", "casco", "GPS", "ropa técnica"],
    languages: ["Francés", "Inglés"],
    price_eur: 45,
    price_unit: "por día",
    rating: 4.5,
    reviews_count: 96,
    verified: true,
    why: "El punto de alquiler mejor valorado de la región para bicicletas de gama alta (carbono, grupo electrónico).",
  },
  {
    id: "gear-summit-cycles",
    type: "producto",
    name: "Summit Cycles — tienda técnica",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    min_level: "cualquiera",
    services: ["bicicletas", "ropa técnica de montaña", "accesorios de nutrición"],
    languages: ["Francés", "Inglés"],
    price_eur: 120,
    price_unit: "kit básico desde",
    rating: 4.7,
    reviews_count: 41,
    verified: true,
    why: "Tienda física en la base de Alpe d'Huez, especializada en equipo para grandes desniveles y frío en altitud.",
  },
  {
    id: "salud-dr-antoine-belrose",
    type: "salud",
    name: "Dr. Antoine Belrose — Cardiología del deporte",
    region: "Alpes (Francia/Italia)",
    country: "Francia",
    min_level: "cualquiera",
    services: ["prueba de esfuerzo", "valoración cardiovascular", "informe de aptitud"],
    certification: "Medicina del Deporte, Universidad de Grenoble",
    languages: ["Francés", "Inglés"],
    price_eur: 140,
    price_unit: "consulta",
    rating: 4.9,
    reviews_count: 27,
    verified: true,
    why: "Especialista en valoración cardiovascular de ciclistas de fondo antes de retos de alto desnivel.",
  },

  // ---- Mallorca (España) ----
  {
    id: "op-mallorca-cycling",
    type: "operador",
    name: "Mallorca Cycling Co.",
    region: "Mallorca (España)",
    country: "España",
    min_level: "intermedio",
    services: ["guía en ruta", "soporte mecánico", "transporte de bici"],
    languages: ["Español", "Inglés", "Alemán"],
    price_eur: 540,
    price_unit: "paquete de 3 días",
    rating: 4.7,
    reviews_count: 210,
    verified: true,
    why: "El operador con más reservas confirmadas de la isla; rutas adaptadas a la Tramuntana según tu nivel real.",
  },
  {
    id: "coach-elena-ruiz",
    type: "coach",
    name: "Elena Ruiz — Rendimiento en carretera",
    region: "Mallorca (España)",
    country: "España",
    min_level: "cualquiera",
    services: ["plan de entrenamiento", "test de potencia", "nutrición deportiva básica"],
    certification: "RFEC Nivel II",
    languages: ["Español", "Inglés"],
    price_eur: 180,
    price_unit: "plan de 6 semanas",
    rating: 4.8,
    reviews_count: 63,
    verified: true,
    why: "Trabaja específicamente la preparación para Sa Calobra y el Puig Major con ciclistas de nivel intermedio.",
  },
  {
    id: "salud-dra-clara-fonseca",
    type: "salud",
    name: "Dra. Clara Fonseca — Medicina deportiva",
    region: "Mallorca (España)",
    country: "España",
    min_level: "cualquiera",
    services: ["prueba de esfuerzo", "valoración cardiovascular", "plan de retorno seguro"],
    certification: "Medicina del Deporte, Universidad de Barcelona",
    languages: ["Español", "Inglés"],
    price_eur: 120,
    price_unit: "consulta",
    rating: 5.0,
    reviews_count: 19,
    verified: true,
    why: "Recomendada cuando el checklist detecta factores de riesgo cardiovascular antes de un reto exigente.",
  },
  {
    id: "gear-mediterraneo-bike-shop",
    type: "producto",
    name: "Mediterráneo Bike Shop",
    region: "Mallorca (España)",
    country: "España",
    min_level: "cualquiera",
    services: ["bicicletas", "ropa técnica", "recambios"],
    languages: ["Español", "Inglés"],
    price_eur: 95,
    price_unit: "kit básico desde",
    rating: 4.6,
    reviews_count: 34,
    verified: true,
    why: "Tienda de referencia en Palma para ciclistas visitantes, con servicio de ajuste de bici el mismo día.",
  },

  // ---- Colorado (EE. UU.) ----
  {
    id: "op-rockies-adventure",
    type: "operador",
    name: "Rockies Adventure Rides",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    min_level: "intermedio-alto",
    services: ["guía en ruta", "soporte mecánico", "aclimatación a la altitud"],
    languages: ["Inglés", "Español"],
    price_eur: 780,
    price_unit: "paquete de 4 días",
    rating: 4.7,
    reviews_count: 88,
    verified: true,
    why: "Incluye un protocolo de aclimatación previo, clave para retos por encima de los 3.500 m como Mount Evans.",
  },
  {
    id: "coach-jake-miller",
    type: "coach",
    name: "Jake Miller — Altitude Coaching",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    min_level: "cualquiera",
    services: ["plan de entrenamiento", "protocolo de altitud", "seguimiento por Garmin"],
    certification: "USA Cycling Level 1",
    languages: ["Inglés"],
    price_eur: 240,
    price_unit: "plan de 8 semanas",
    rating: 4.8,
    reviews_count: 45,
    verified: true,
    why: "Especializado en preparar ciclistas de fuera de Colorado para el efecto de la altitud en el rendimiento.",
  },
  {
    id: "rental-rockies-gear",
    type: "alquiler",
    name: "Rockies Gear Rental",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    min_level: "cualquiera",
    services: ["bicicleta de carretera", "casco", "capas térmicas"],
    languages: ["Inglés"],
    price_eur: 50,
    price_unit: "por día",
    rating: 4.4,
    reviews_count: 39,
    verified: true,
    why: "Incluye capas térmicas en el alquiler — necesarias por el cambio brusco de temperatura en altitud.",
  },
  {
    id: "salud-dr-james-cole",
    type: "salud",
    name: "Dr. James Cole — Medicina de altitud",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    min_level: "cualquiera",
    services: ["valoración cardiovascular", "protocolo de altitud", "informe de aptitud"],
    certification: "Wilderness Medical Society",
    languages: ["Inglés"],
    price_eur: 160,
    price_unit: "consulta",
    rating: 4.9,
    reviews_count: 22,
    verified: true,
    why: "Referencia local en medicina de altitud; recomendado especialmente para retos por encima de 3.000 m.",
  },
  {
    id: "gear-highaltitude-outfitters",
    type: "producto",
    name: "High Altitude Outfitters",
    region: "Colorado (EE. UU.)",
    country: "Estados Unidos",
    min_level: "cualquiera",
    services: ["bicicletas", "ropa técnica de altitud", "accesorios de nutrición"],
    languages: ["Inglés"],
    price_eur: 130,
    price_unit: "kit básico desde",
    rating: 4.5,
    reviews_count: 28,
    verified: true,
    why: "Equipo pensado para grandes variaciones térmicas — habitual en ascensos de más de 2.000 m de desnivel.",
  },

  // ---- Santa Catarina (Brasil) ----
  {
    id: "op-serra-catarinense",
    type: "operador",
    name: "Serra Catarinense Bike Tours",
    region: "Santa Catarina (Brasil)",
    country: "Brasil",
    min_level: "intermedio",
    services: ["guía en ruta", "soporte mecánico", "transporte desde Florianópolis"],
    languages: ["Portugués", "Español", "Inglés"],
    price_eur: 420,
    price_unit: "paquete de 3 días",
    rating: 4.7,
    reviews_count: 67,
    verified: true,
    why: "El operador local con más reservas confirmadas para la Serra do Rio do Rastro y rutas cercanas.",
  },
  {
    id: "coach-carlos-almeida",
    type: "coach",
    name: "Carlos Almeida — Preparação para serras",
    region: "Santa Catarina (Brasil)",
    country: "Brasil",
    min_level: "cualquiera",
    services: ["plan de entrenamiento", "test de umbral", "seguimiento por Strava"],
    certification: "CBC Nível II",
    languages: ["Portugués", "Español"],
    price_eur: 150,
    price_unit: "plan de 6 semanas",
    rating: 4.8,
    reviews_count: 31,
    verified: true,
    why: "Conoce de primera mano las rampas de hasta el 15% de la Serra do Rio do Rastro.",
  },
  {
    id: "salud-dr-henrique-santos",
    type: "salud",
    name: "Dr. Henrique Santos — Cardiologia do esporte",
    region: "Santa Catarina (Brasil)",
    country: "Brasil",
    min_level: "cualquiera",
    services: ["prueba de esfuerzo", "valoración cardiovascular", "informe de aptitud"],
    certification: "Sociedade Brasileira de Medicina do Exercício e do Esporte",
    languages: ["Portugués", "Español"],
    price_eur: 90,
    price_unit: "consulta",
    rating: 4.9,
    reviews_count: 24,
    verified: true,
    why: "Recomendado por el checklist cuando se detecta un factor de riesgo cardiovascular antes de rampas pronunciadas.",
  },
  {
    id: "gear-tropical-wear",
    type: "producto",
    name: "Tropical Wear — ropa técnica",
    region: "Santa Catarina (Brasil)",
    country: "Brasil",
    min_level: "cualquiera",
    services: ["ropa técnica de clima húmedo", "accesorios de nutrición", "recambios"],
    languages: ["Portugués", "Español"],
    price_eur: 70,
    price_unit: "kit básico desde",
    rating: 4.5,
    reviews_count: 18,
    verified: true,
    why: "Ropa pensada para el calor y la humedad de la Serra Catarinense, distinta de la ropa alpina de invierno.",
  },
];
